- name: Обновление кэша и системных пакетов для Debian-family
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Обновление кэша и системных пакетов для RedHat-family (AlmaLinux)
  dnf:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"

- name: Установка единого часового пояса
  timezone:
    name: Asia/Yakutsk

- name: Настройка безпарольного sudo для appuser
  copy:
    content: "appuser ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/appuser
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s     
